# Mall Customer Segmentation - Data Cleaning and Preprocessing
## Introduction
This notebook focuses on cleaning and validating the Mall Customer Segmentation dataset. The objective is to review the dataset structure, identify potential data quality issues, standardize column names, and verify the consistency of customer demographic and spending information. The cleaned dataset will be prepared for future analysis and customer segmentation tasks.

### 1. Import Library

In [1]:
import pandas as pd

### 2. Load Dataset

In [ ]:
df = pd.read_csv("mall_customer_raw.csv")

### 3. Data Overview

In [3]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [5]:
df.describe(include="all")

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)
count,200.000000,200,200.000000,200.000000,200.000000
unique,NaN,2,NaN,NaN,NaN
top,NaN,Female,NaN,NaN,NaN
freq,NaN,112,NaN,NaN,NaN
mean,100.500000,NaN,38.850000,60.560000,50.200000
std,57.879185,NaN,13.969007,26.264721,25.823522
min,1.000000,NaN,18.000000,15.000000,1.000000
25%,50.750000,NaN,28.750000,41.500000,34.750000
50%,100.500000,NaN,36.000000,61.500000,50.000000
75%,150.250000,NaN,49.000000,78.000000,73.000000
max,200.000000,NaN,70.000000,137.000000,99.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

### 3. Column Name Standardization

In [8]:
df.columns = (df.columns.str.lower().str.replace(" ", "_").str.replace("(", "", regex=False).str.replace(")", "", regex=False))

### 4. Categorical Data Inspection

In [10]:
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [11]:
df["gender"].value_counts()

gender
Female    112
Male       88
Name: count, dtype: int64

### 5. Duplicate Record Check

In [12]:
df.duplicated().sum()

np.int64(0)

### 6. Final Data Quality Validation

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customerid            200 non-null    int64
 1   gender                200 non-null    object
 2   age                   200 non-null    int64
 3   annual_income_k$      200 non-null    int64
 4   spending_score_1-100  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

### 7. Export Cleaned Dataset

In [ ]:
df.to_csv("mall_customer_cleaned.csv")