# Sales Data - Data Cleaning and Preprocessing
## Introduction
This notebook focuses on cleaning and preprocessing the Sales Export 2019–2020 dataset. The objective is to review dataset structure, standardize column names, correct data types, and validate overall data quality. The cleaned dataset will be prepared for future sales analysis and reporting.

### 1. Import Library

In [1]:
import pandas as pd

### 2. Load Dataset

In [ ]:
df = pd.read_csv("sales_data_raw.csv")

### 3. Dataset Overview

In [3]:
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

In [4]:
df.describe(include="all")

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
count,1000,1000,1000.000000,1000,1000,1000,1000,1000,1000,1000
unique,15,1000,NaN,536,10,75,15,35,3,1000
top,Portugal,"17,524.02",NaN,3/5/2020,Clothing,Johns and Sons,Celine Tumasian,Amelina Piscopiello,PC,70-0511466
freq,239,1,NaN,5,155,142,239,56,785,1
mean,NaN,NaN,94369.310990,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,51540.020934,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,12113.680000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,54247.957500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,87094.760000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,125570.837500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,304701.430000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            1000 non-null   object
 1    order_value_EUR   1000 non-null   object
 2    cost              1000 non-null   float64
 3   date               1000 non-null   object
 4   category           1000 non-null   object
 5   customer_name      1000 non-null   object
 6   sales_manager      1000 non-null   object
 7   sales_rep          1000 non-null   object
 8   device_type        1000 non-null   object
 9   order_id           1000 non-null   object
dtypes: float64(1), object(9)
memory usage: 78.3+ KB

### 4. Column Name Standardization

In [6]:
df.columns = (df.columns.str.strip().str.lower())

### 5. Data Type Validation and Correction

In [7]:
df["order_value_eur"] = (df["order_value_eur"].str.replace(",", "", regex=False).astype(float))

In [8]:
df["date"] = pd.to_datetime(df["date"])

### 6. Handling Missing Values

In [9]:
df.isnull().sum()

country            0
order_value_eur    0
cost               0
date               0
category           0
customer_name      0
sales_manager      0
sales_rep          0
device_type        0
order_id           0
dtype: int64

### 7. Catregorical Data Inspection

In [10]:
df["country"].unique()

array(['Sweden', 'Finland', 'Portugal', 'Spain', 'UK', 'France',
       'Netherlands', 'Belgium', 'Bulgaria', 'Luxembourg', 'Italy',
       'Ireland', 'Germany', 'Denmark', 'Austria'], dtype=object)

In [11]:
df["category"].unique()

array(['Books', 'Games', 'Clothing', 'Beauty', 'Accessories',
       'Appliances', 'Smartphones', 'Outdoors', 'Electronics', 'Other'],
      dtype=object)

In [12]:
df["device_type"].unique()

array(['Mobile', 'PC', 'Tablet'], dtype=object)

### 8. Duplicate Record Check

In [13]:
df.duplicated().sum()

np.int64(0)

### 9. Final Data Quality Validation

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          1000 non-null   object
 1   order_value_eur  1000 non-null   float64
 2   cost             1000 non-null   float64
 3   date             1000 non-null   datetime64[ns]
 4   category         1000 non-null   object
 5   customer_name    1000 non-null   object
 6   sales_manager    1000 non-null   object
 7   sales_rep        1000 non-null   object
 8   device_type      1000 non-null   object
 9   order_id         1000 non-null   object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 78.3+ KB

### 10. Export Cleaned Dataset

In [ ]:
df.to_csv("sales_data_cleaned.csv", index=False)